# Generated by Django 3.2.9 on 2021-11-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('sku', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('finishes', models.CharField(blank=True, max_length=200, null=True)),
                ('category_name', models.CharField(choices=[('Adhesive Sealants', 'Adhesive Sealants'), ('Locks', 'Locks'), ('Hinges', 'Hinges'), ('Shelf Support', 'Shelf Support'), ('Nails Staples', 'Nails Staples'), ('Screws', 'Screws'), ('Plumbing', 'Plumbing'), ('Tools', 'Tools'), ('Abrasives', 'Abrasives'), ('Fasteners', 'Fasteners'), ('Locks', 'Locks'), ('Cleaning Supplies', 'Cleaning Supplies'), ('Paint', 'Paint'), ('Hardware', 'Hardware'), ('Misc', 'Misc')], default=('Adhesive Sealants', 'Adhesive Sealants'), max_length=200, null=True)),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='Is in stock?')),
            ],
        ),
    ]
