# Generated by Django 3.2.9 on 2021-11-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211110_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='category_url',
            field=models.CharField(blank=True, default=('/category/kitchen', '/category/kitchen'), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_slider'),
        ),
    ]
