# Generated by Django 3.2.9 on 2021-11-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_homeslider_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='category_url',
            field=models.CharField(blank=True, choices=[('/category/kitchen', '/category/kitchen'), ('/category/bathroom', '/category/bathroom'), ('/category/commercial', '/category/commercial')], default=('/category/kitchen', '/category/kitchen'), max_length=200, null=True),
        ),
    ]
