# Generated by Django 3.2.9 on 2022-01-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20220115_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
